### ISSUE TITLE
Suggestion for revised banter timing subcomponent name

### ISSUE THREAD

**Issue by agb1** [Argent77/DjinniCompanion#1]
Change Banter Frequency for the djinni (does not affect other NPCs - default: 60 Minutes)

Making it very clear that this doesn't interact with other mods that tweak banter timing.

**Comment by Argent77** [comment]
The current component name already indicates that it only affects the djinni banters. But I can try to make it clearer.

How about this line?
`Change banter frequency between Afaaq and the protagonist? (Default: 60 Minutes)`

**Comment by agb1** [comment]
I'm aiming to reduce confusion with mods like BG1NPC that have banter accelerator components.

To make it explicit, but shorter, maybe this?

Change banter frequency (only affects the djinni - default: 60 Minutes)?

**Comment by Argent77** [comment]
Yes, I can do that.
