### ISSUE TITLE
Afaaq is getting married.

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/DjinniCompanion#14]
After spending many years alone in his battle, Afaaq decided it is time for a wife.

As a proper modern djinni, Afaaq prefers the spouse to be pretty. He did find some
old books that showcased how female djinni may look like. Like this:

https://i.imgur.com/i7Lvp12.jpeg

She even holds up a bottle! How nice.

How could Afaaq get a spouse though?

Well - there may be some quest options:

- An evil mage may hold other djinni captive in some area, like a cave or something. Could be an ogre mage or so. Or an orc mage. Experimenting with them. Perhaps trying to mate a djinni and an efreeti.
- It could be an old, broken bottle that is found somewhere. Since the old bottle is broken, she who is inside could just move in with Afaaq.

Hmm.

Anyway. I don't have a great suggestion, but if you are ever bored and also feel Afaaq needs more company in his bottle, perhaps something could be considered. While a female spouse may be best, it could also be other things for entertainment, like dancing kobolds or flying fairies or so. Anything to make Afaaq less bored in the bottle.

**Comment by Argent77** [comment]
Well, you can visit Afaaq in the lamp at some point of the game. (But I admit that I haven't really made that experience interesting in some way.)
