### ISSUE TITLE
[FAQ entry] Could it be mentioned where the djinni can be found in the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/DjinniCompanion#3]
[FAQ entry] Could it be mentioned where the djinni can be found in the main README?

I install quite many mods and then I don't really know what is all going on, so having
a documented "this is where to start the quest/companion run" really helps. Thank
you for reading this and possibly considering.

**Comment by Argent77** [comment]
That's already answered in the [FAQ section of the Readme](https://argent77.github.io/DjinniCompanion/index.html#faq) (first two questions). It doesn't reveal too many details to keep spoiling on a minimum, but the quest leading to the djinni should be rather straightforward.

The readme is included in the mod package, and the online version is also linked in the GitHub project readme.
