### ISSUE TITLE
FAQ / Hint: could the main README give a hint where to find him?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/DjinniCompanion#6]
FAQ / Hint: could the main README give a hint where to find him?

Right now I am not sure where he could be found or obtained.

**Comment by Argent77** [comment]
The readme of the GitHub repo is just meant as a quick mod overview. For detailed mod information I'd suggest to read the [official readme](https://argent77.github.io/DjinniCompanion/index.html) of the mod. Your question should be answered in the FAQ section.
