### ISSUE TITLE
When I chose to install this mod in Chinese on BG2EE and checked the dialog.tlk, I found some English text.

### ISSUE THREAD

**Issue by Lzw104522773** [Argent77/DjinniCompanion#9]
When I chose to install this mod in Chinese on BG2EE and checked the dialog.tlk, I found some English text.

![QQ截图20240702172651](https://github.com/Argent77/DjinniCompanion/assets/149546927/34b3b3e8-2128-4012-910f-33b1fa5c20d1)

![QQ截图20240702172716](https://github.com/Argent77/DjinniCompanion/assets/149546927/5b59e45d-2ea3-4f57-b455-167fb90eab5f)

**Comment by Argent77** [comment]
Good catch! It looks like several lines haven't been traified yet. I'll fix it asap.

**Comment by Argent77** [comment]
Fixed in 4edede7.

Most lines already existed in the tra files. Some lines are used internally or for diagnostic reasons and don't need to be translated. There is only one new line to translate in `quest3.tra`.
